name: Build myface EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install Build Tools (CMake)
      run: |
        pip install cmake

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt

    - name: Patch Face Recognition (Prevent loading heavy unused models)
      run: |
        python -c "import face_recognition.api; path = face_recognition.api.__file__; content = open(path).read(); content = content.replace('pose_predictor_68_point = dlib.shape_predictor(predictor_68_point_model)', 'pose_predictor_68_point = None'); content = content.replace('cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)', 'cnn_face_detector = None'); open(path, 'w').write(content)"


    - name: Download and extract UPX
      run: |
        Invoke-WebRequest -Uri https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-win64.zip -OutFile upx.zip
        Expand-Archive upx.zip -DestinationPath .
        echo "$PWD/upx-4.2.2-win64" >> $env:GITHUB_PATH

    - name: Get Face Recognition Models Path
      id: fr_path
      run: |
        $FR_DIR = python -c "import face_recognition_models; import os; print(os.path.dirname(face_recognition_models.__file__))"
        echo "FR_DIR=$FR_DIR" >> $env:GITHUB_ENV

    - name: Build Standalone Executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name myface `
          --exclude-module scipy `
          --exclude-module matplotlib `
          --exclude-module pandas `
          --exclude-module PyQt5 `
          --exclude-module notebook `
          --exclude-module IPython `
          --exclude-module PIL.ImageQt `
          --exclude-module PIL.ImageDraw `
          --add-data "${{ env.FR_DIR }}\models\mmod_human_face_detector.dat;face_recognition_models\models" `
          --add-data "${{ env.FR_DIR }}\models\shape_predictor_5_face_landmarks.dat;face_recognition_models\models" `
          --add-data "${{ env.FR_DIR }}\models\dlib_face_recognition_resnet_model_v1.dat;face_recognition_models\models" `
          --upx-dir upx-4.2.2-win64 `
          --upx-exclude "vcruntime140.dll" `
          --upx-exclude "vcruntime140_1.dll" `
          myface.py

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myface-Windows
        path: dist/myface.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/myface.exe
        tag_name: v1.0.0
        name: Version 1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
